server.address=127.0.0.1
server.port=8080
server.tomcat.threads.max=24
server.tomcat.max-connections=64
server.tomcat.accept-count=16
spring.mvc.async.request-timeout=30000
spring.jackson.serialization.write-dates-as-timestamps=false
server.error.include-message=never

spring.jackson.deserialization.fail-on-unknown-properties=true
